spring:
  application:
    name: zuul

server:
  port: 9000

# -- Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# -- Zuul
zuul:
  routes:
    user-service:
      path: /demo/v0.1/users/**
      service-id: USER-SERVICE
      stripPrefix: false
    store-service:
      path: /demo/v0.1/stores/**
      service-id: STORE-SERVICE
      stripPrefix: false